// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoList.Infrastructure;

#nullable disable

namespace ToDoList.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250129213550_Initial_Database")]
    partial class Initial_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoList.Domain.Tasks.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("ToDoList.Domain.Users.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ebd92069-30cd-4d60-8ac2-9fa5fd384ed5"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 7, DateTimeKind.Utc).AddTicks(7560),
                            CreatedBy = "System",
                            Description = "Allows the user to manage other users within the application. This includes creating new user accounts, updating user information, assigning or modifying roles and permissions, deactivating or deleting accounts, and overseeing user activity as needed. This permission is typically reserved for administrators or higher-level users.",
                            Name = "Manage Users"
                        },
                        new
                        {
                            Id = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 7, DateTimeKind.Utc).AddTicks(7560),
                            CreatedBy = "System",
                            Description = "Allows the user to add new tasks to the list, assigning a description, and any other relevant details.",
                            Name = "Create Task"
                        },
                        new
                        {
                            Id = new Guid("2ee1b98c-3aac-4eba-aaa6-210c6a4133a3"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 7, DateTimeKind.Utc).AddTicks(7560),
                            CreatedBy = "System",
                            Description = "Allows the user to view existing tasks, including their properties, and additional details.",
                            Name = "Read Task"
                        },
                        new
                        {
                            Id = new Guid("c0161d02-d8df-491b-b8c0-78eafaaf3b1c"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 7, DateTimeKind.Utc).AddTicks(7560),
                            CreatedBy = "System",
                            Description = "Allows the user to modify existing tasks, including changing the description, status or any other task attributes",
                            Name = "Update Task"
                        },
                        new
                        {
                            Id = new Guid("61c1c4e4-468f-4825-8097-4e0611304c85"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 7, DateTimeKind.Utc).AddTicks(7560),
                            CreatedBy = "System",
                            Description = "Allows the user to remove tasks from the list, either deleting a single task or multiple selected tasks.",
                            Name = "Delete Task"
                        });
                });

            modelBuilder.Entity("ToDoList.Domain.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 7, DateTimeKind.Utc).AddTicks(8280),
                            CreatedBy = "System",
                            Description = "Has full access to the application, including managing users, assigning roles, and performing all task-related actions (create, read, update, and delete). Admins can also configure system settings and oversee overall application functionality.",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("f55cbc28-01c4-427d-9a40-ed271472da7d"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 7, DateTimeKind.Utc).AddTicks(8280),
                            CreatedBy = "System",
                            Description = "Has advanced permissions, allowing them to create, read, update, and delete tasks. However, they do not have administrative privileges such as user management or system settings modification.",
                            Name = "Level 2"
                        },
                        new
                        {
                            Id = new Guid("cce065f9-acb8-429d-8deb-3e75f7b1e2a0"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 7, DateTimeKind.Utc).AddTicks(8280),
                            CreatedBy = "System",
                            Description = "Has basic permissions, typically limited to creating and reading their own tasks. Level 1 users do not have the ability to update or delete tasks, nor can they manage other users or system settings.",
                            Name = "Level 1"
                        });
                });

            modelBuilder.Entity("ToDoList.Domain.Users.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            PermissionId = new Guid("ebd92069-30cd-4d60-8ac2-9fa5fd384ed5"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8330),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            PermissionId = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8330),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            PermissionId = new Guid("2ee1b98c-3aac-4eba-aaa6-210c6a4133a3"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8330),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            PermissionId = new Guid("c0161d02-d8df-491b-b8c0-78eafaaf3b1c"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8330),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            PermissionId = new Guid("61c1c4e4-468f-4825-8097-4e0611304c85"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8330),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("f55cbc28-01c4-427d-9a40-ed271472da7d"),
                            PermissionId = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8330),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("f55cbc28-01c4-427d-9a40-ed271472da7d"),
                            PermissionId = new Guid("2ee1b98c-3aac-4eba-aaa6-210c6a4133a3"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8340),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("f55cbc28-01c4-427d-9a40-ed271472da7d"),
                            PermissionId = new Guid("c0161d02-d8df-491b-b8c0-78eafaaf3b1c"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8340),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("f55cbc28-01c4-427d-9a40-ed271472da7d"),
                            PermissionId = new Guid("61c1c4e4-468f-4825-8097-4e0611304c85"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8340),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("cce065f9-acb8-429d-8deb-3e75f7b1e2a0"),
                            PermissionId = new Guid("d2b3fb32-95c1-4703-aec2-c98a36762138"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8340),
                            CreatedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("cce065f9-acb8-429d-8deb-3e75f7b1e2a0"),
                            PermissionId = new Guid("2ee1b98c-3aac-4eba-aaa6-210c6a4133a3"),
                            CreatedAtUtc = new DateTime(2025, 1, 29, 21, 35, 50, 8, DateTimeKind.Utc).AddTicks(8340),
                            CreatedBy = "System"
                        });
                });

            modelBuilder.Entity("ToDoList.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ToDoList.Domain.Users.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermission", (string)null);
                });

            modelBuilder.Entity("ToDoList.Domain.Tasks.Task", b =>
                {
                    b.HasOne("ToDoList.Domain.Users.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ToDoList.Domain.Users.RolePermission", b =>
                {
                    b.HasOne("ToDoList.Domain.Users.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoList.Domain.Users.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ToDoList.Domain.Users.UserPermission", b =>
                {
                    b.HasOne("ToDoList.Domain.Users.User", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoList.Domain.Users.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoList.Domain.Users.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ToDoList.Domain.Users.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
